### ISSUE TITLE
Issue with README example

### ISSUE THREAD

**Issue by blakexcosta** [dorian3343/simple_dic#1]
I couldn't help but notice when attempting to run with the example code provided, that the `push()` function is expecting a String() to be returned with the result. This causes an error as `my_dict.push("age".to_string(), 25).unwrap();` uses an integer to push to the simulated dict/Hashmap but the `Result<(), String>` is expecting a String type.

This error message is as follows (I created a `main.rs` file to test quick):

```
error[E0308]: mismatched types
  --> src\main.rs:9:37
   |
6  |     my_dict
   |     ------- ... which causes `my_dict` to have type `Dictionary<String>`
7  |         .push("name".to_string(), "John".to_string())
   |                                   ------------------ this argument has type `String`...
8  |         .unwrap();
9  |     my_dict.push("age".to_string(), 25).unwrap(); // found issue in push?
   |             ----                    ^^- help: try using a conversion method: `.to_string()`
   |             |                       |
   |             |                       expected `String`, found integer
   |             arguments to this method are incorrect
   |
note: method defined here
  --> D:\Development\Game_Design\Rust_Projects\simple_dic\src\lib.rs:16:12
   |
16 |     pub fn push(&mut self, key: String, value: T) -> Result<(), String> {
   |            ^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `simple_dic` (bin "simple_dic") due to previous error
```

This could possibly be resolved by having a type that implements std::fmt::Display for the return type? Such as the following code:

```rust
//Pushes a key/value pair to the end
pub fn push<E>(&mut self, key: String, value: T) -> Result<(), E>
where
    E: std::fmt::Display,
{
    if self.key.contains(&key) {
        return Err(format!("Key: '{}' does not exist.", key));
    } else {
        self.key.push(key);
        self.value.push(value);
        Ok(())
    }
}
```

Though this will not necessarily compile as is, just a thought/possible solution. Unless of course you do want to return a `String` type and just change the example to `my_dict.push("age".to_string(), 25.to_string()).unwrap();`. It's a bandaid solution but it works for the time being as well.

**Comment by dorian3343** [comment]
My bad, will fix the README, wrote that example on an old version of the code. <3
